### ISSUE TITLE
issues after pushing to github pages

### ISSUE THREAD

**Issue by lgwapnitsky** [gethugothemes/restaurant-hugo#23]
just using demo info, i'm getting pages without template settings when i push to github pages. I've deleted and recommitted multiple times.

leisurefoodlarry.github.io.

**Comment by lgwapnitsky** [comment]
fyi, same files worked fine at leisurefoodlarry.com - no changes, just a git pull.

**Comment by somratpro** [comment]
Hello @lgwapnitsky 

I am not sure what you are talking about. but if you have any issue with a broken site after pushing to Github, make sure you are using the correct baseURL in `config.toml` file when you are generating the public folder. In your case, the baseURL would be `https://leisurefoodlarry.github.io` I think.

**Comment by somratpro** [comment]
hey @lgwapnitsky 

I think your issue has been solved. so I am closing this issue, if you have any more queries you can re-open this issue or create a new one. thank you
