### ISSUE TITLE
Blog posts not showing on iOS Devices

### ISSUE THREAD

**Issue by gonz23** [gethugothemes/restaurant-hugo#24]
On Safari on iPhone the Blog only shows the pictures without description and selecting them only causes the animation to start.

On Safari on Mac Blog posts show up alright on Main page, but on selection show an entirely empty page.

**Comment by gonz23** [comment]
Update: It seems to be only the case for the demo page

**Comment by somratpro** [comment]
Hello @gonz23 

Currently, we don't have any IOS device to check it. Sorry!

**Comment by gonz23** [comment]
Hi @somratpro !

The problem is solely related to the demo page. When actually using the Theme the problem disappears. Maybe just republish the demo page. On my end the problem is solved with actually using the theme, so it'd be fine to close the issue. Thanks for your response!
